### ISSUE TITLE
大佬请问这个 yesplay退出之后 歌词组件会停留在上一句歌词的状态（貌似没有做退出处理

### ISSUE THREAD

**Issue by yoyos12138** [zsiothsu/org.kde.plasma.yesplaymusic-lyrics#1]
![截图_20240116_012856](https://github.com/zsiothsu/org.kde.plasma.yesplaymusic-lyrics/assets/116458182/3445ae3d-a84d-4311-8256-cec5f1a4a724)
顺便问问 大佬的kde组件开发怎么学的（

**Comment by zsiothsu** [comment]
是的，还没想好退出逻辑怎么写，有空的话我再试试能不能实现，现在社畜一个（
kde组件的话官方有hello world示例 https://github.com/Zren/plasmoid-helloworldplugin
其实就是qml嵌js，网上搜qml教程就行，有些涉及到kde的部分直接参考例程写的，~/.local/share/plasma/plasmoids/和/usr/share/plasma/plasmoids 底下有很多可以参考

**Comment by zsiothsu** [comment]
话说这个插件的本意是放在panel里面的，直接贴在桌面上的话不太好看（因为没写桌面模式的代码

**Comment by zsiothsu** [comment]
现在加上了，怕误杀所以设置超时5次之后再让歌词消失，你看看现在能不能用
