### ISSUE TITLE
关于歌词api超时导致卡死的反馈

### ISSUE THREAD

**Issue by izumisagirii** [zsiothsu/org.kde.plasma.yesplaymusic-lyrics#2]
arch+kde

`xhr.open('GET', 'http://127.0.0.1:10754/lyric?id=' + tracker.id, true)`这里会卡若干分钟之后返回502，貌似在此期间程序会循环GET请求导致plasmashell崩溃

出于强迫症看了ypm的repo，但是没有定位到歌词api出错的原理，yesplaymusic一直是一年前的版本，字幕没有出错

**Comment by izumisagirii** [comment]
api超时是由于我的网络环境造成的抽风

**Comment by zsiothsu** [comment]
我也是第一次写js（本来想着都是本地网络应用应该不会出什么问题。会超时的话我想想怎么解决吧QAQ

**Comment by zsiothsu** [comment]
看了一下 `xhr.open('GET', 'http://127.0.0.1:10754/lyric?id=' + tracker.id, true)`是旧版代码里面的，应该是因为我没有发新的release。。。新版的代码我稍微改了一下，可以clone最新的代码使用。之后kde store那边我也同步上去吧
