### ISSUE TITLE
希望加上同时显示歌词原文和译文的选项

### ISSUE THREAD

**Issue by ShoreNinth** [zsiothsu/org.kde.plasma.yesplaymusic-lyrics#4]
首先感谢大佬的付出，让我在更新KDE6后还能继续用上歌词显示插件。

但我有个不情之请：@LiYuLin大佬的插件支持 原文+译文 同时显示，我转过来后有点不习惯。

不是什么刚需，但如果大佬能采纳，那么感激不尽

**Comment by zsiothsu** [comment]
能指路一下插件的位置吗, 我下下来试一下效果(

**Comment by zsiothsu** [comment]
kde6是热心网友@izumisagirii帮忙适配的，我也是只是merge了一下_(:з」∠)_

**Comment by zsiothsu** [comment]
> 能指路一下插件的位置吗, 我下下来试一下效果
哦哦看到了，原来是贴吧的昵称不是github的（

**Comment by zsiothsu** [comment]
我这几天有空再加一下吧，感谢你的反馈！

**Comment by zsiothsu** [comment]
已经加上了哦，加了一个第二语言的选项，然后显示在同一行上面。如果状态栏中间放的是时钟的话可能有点挤
