### ISSUE TITLE
转义字符兼容问题

### ISSUE THREAD

**Issue by Yastruhank** [zsiothsu/org.kde.plasma.yesplaymusic-lyrics#5]
似乎歌词中的转义字符不会被正确翻译，例如 \"
以下为插件中显示的歌词
![1](https://github.com/zsiothsu/org.kde.plasma.yesplaymusic-lyrics/assets/29678135/1381274d-e02a-49d7-8bbd-934b0a8e9342)
以下为yesplaymusic中显示的原始歌词
![2](https://github.com/zsiothsu/org.kde.plasma.yesplaymusic-lyrics/assets/29678135/efd5980d-96e6-4aaf-9cef-d67ec46793b2)

**Comment by zsiothsu** [comment]
原来还有转义吗，我自己用居然没发觉_(:з」∠)_。感谢反馈！

**Comment by zsiothsu** [comment]
更新了一下代码，现在应该解决了_(:з」∠)_
