### ISSUE TITLE
部分歌曲解析失败

### ISSUE THREAD

**Issue by huvz04** [zsiothsu/org.kde.plasma.yesplaymusic-lyrics#6]
经过本地测试，发现部分歌曲接口已经获取到original。id_original_cache的赋值好像出现了问题

复现数据：
测试歌曲：I I I    宝鐘マリン/Kobo Kanaeru
id：2156449786
赋值打印时正常，但是id_original_cache在第二轮循环中值变成了-2138517510，导致渲染进入了死循环。
初步猜测可能是qml的int类型丢失精度？于是更换为real就解决了

不知道作者是否接受pr？

**Comment by huvz04** [comment]
另外，个人写了单/双行歌词的兼容的feat能否一起提交？（毕竟单行空格分割双语个人用着有点怪）
开启双语换行歌词的效果如下，主要是水平居中+换行
![图片](https://github.com/user-attachments/assets/e22d023f-a4c5-4a46-bb74-31b6be9638e5)
切换回单语还是垂直居中的
![图片](https://github.com/user-attachments/assets/50840a90-7aae-43a2-9b69-98631ab03d83)

**Comment by zsiothsu** [comment]
可以发起pr，感谢测试！

**Comment by zsiothsu** [comment]
抱歉最近看消息比较慢_(:з」∠)_

**Comment by zsiothsu** [comment]
✿ヽ(°▽°)ノ✿已合并
